### ISSUE TITLE
Bring Back to Top button on top

### ISSUE THREAD

**Issue by abhijit49** [abhijit49/E-Commerce-Website-CARA-#19]

**Comment by Aspireve** [comment]
Hey Hi @abhijit49 !! Could I work on this issue.
Also could you explain what do you mean by bringing that button to the top cause I think The `Back To Top` button functions correctly.
Would you like the `Bring to Top` button to have an animation of going up?

**Comment by abhijit49** [comment]
![cart](https://user-images.githubusercontent.com/91731000/198816395-7e6d5256-f0a6-4681-8eb4-27c6d15663a2.png)
See if you understand!

**Comment by Aspireve** [comment]
Ohh you meant on the mobile version.
Yup Ill do it soon

**Comment by Aspireve** [comment]
# Developer Update 1
Hi @abhijit49,
I worked on this issue and solved it
Here are the screen recordings of the original and final versions
|| Original Website | My Edited Version |
|----|----|----|
| **Video** |![ezgif com-gif-maker](https://user-images.githubusercontent.com/93852415/198840863-1ef57f18-bcb3-4ce4-8f74-de305d7c9965.gif)| ![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/93852415/198841035-09183785-012d-4f69-a45d-958f069075ed.gif)|
| **Image** |![image](https://user-images.githubusercontent.com/93852415/198840994-bf7524bf-3e39-481d-8b27-5b9f5225b826.png)|![image](https://user-images.githubusercontent.com/93852415/198840925-5eee0f83-843d-4149-b044-9b57e07d71d1.png)|

**Comment by abhijit49** [comment]
good

**Comment by Aspireve** [comment]
Ok Ill make the PR now
