### ISSUE TITLE
Add some text to about section

### ISSUE THREAD

**Issue by abhijit49** [abhijit49/E-Commerce-Website-CARA-#3]
Want to add a few points to the  'Who we are ' section part

**Comment by adityabisoyi** [comment]
I would like to work on this. Please assign this to me.

**Comment by Manish-Syal123** [comment]
Text added to About section https://github.com/abhijit49/E-Commerce-Website-CARA-/pull/13

**Comment by abhijit49** [comment]
issue closed as of now
