### ISSUE TITLE
Improve cart.html page

### ISSUE THREAD

**Issue by abhijit49** [abhijit49/E-Commerce-Website-CARA-#7]
Add table rows and columns like proper cart would look

**Comment by Manish-Syal123** [comment]
Can you show one screen shot of others websits.
So that I can get to know that how you want your cart page.

**Comment by codesmith25103** [comment]
I want to work on this issue. Can you assign me this issue?

**Comment by Jasleen-001** [comment]
Hey,can I work on this issue?

**Comment by abhijit49** [comment]
![cart page example](https://user-images.githubusercontent.com/91731000/197409374-de7ab2d7-3c68-4f2a-befd-3e22335cc39d.png)

**Comment by Manish-Syal123** [comment]
Improved cart.html https://github.com/abhijit49/E-Commerce-Website-CARA-/pull/14
